image: Visual Studio 2019

clone_depth: 5

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore AndroidAppVeyor.sln

configuration: Release

build:
  project: AndroidAppVeyor.sln
  verbosity: normal
