image: Visual Studio 2017

clone_depth: 5

cache:
  - 'C:\Microsoft\AndroidNDK64'

environment:
  VS_NdkRoot: 'C:\Microsoft\AndroidNDK64\android-ndk-r15c'

install:
  - ps: Get-Location
  - ps: .\install.ps1

build_script:
  - echo Building solution
  - msbuild AndroidAppVeyor.sln -v:m -t:Restore;Build -p:Configuration=Release -p:Platform=ARM -l:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - echo Building APK
  - msbuild AndroidAppVeyor\AndroidAppVeyor.csproj -v:m -t:PackageForAndroid -p:Configuration=Release -p:Platform=ARM -p:OutputPath=Bin\Release -l:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: Get-ChildItem -Path AndroidAppVeyor\Bin\Release


#before_build:
#  - nuget restore AndroidAppVeyor.sln

#configuration: Release

#build:
#  project: AndroidAppVeyor.sln
#  verbosity: normal
