image: Visual Studio 2017

clone_depth: 5

cache:
  - C:\Microsoft\AndroidNDK64

install:
  - ps: get-psdrive
  - ps: get-item -path HKCU:\Software\Microsoft\VisualStudio\SecondaryInstaller\VC
  - ps: Get-Location
  - ps: .\install.ps1

before_build:
  - nuget restore AndroidAppVeyor.sln

configuration: Release

build:
  project: AndroidAppVeyor.sln
  verbosity: normal
