image: Visual Studio 2017

clone_depth: 5

cache:
  - C:\Microsoft\AndroidNDK64

environment:
  VS_NdkRoot: 'C:\Microsoft\AndroidNDK64\android-ndk-r15c'

install:
  - ps: Get-Location
  - ps: .\install.ps1

before_build:
  - nuget restore AndroidAppVeyor.sln

configuration: Release

build:
  project: AndroidAppVeyor.sln
  verbosity: normal
