image: Visual Studio 2017

clone_depth: 5

environment:
#  VS_NdkRoot: 'C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17'

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore AndroidAppVeyor.sln

configuration: Release

build:
  project: AndroidAppVeyor.sln
  verbosity: normal
