image: Visual Studio 2017

clone_depth: 5

#cache:
#  - packages -> **\packages.config

install:
  - ps: get-location
  - ps: .\install.ps1
  - ps: $ndkDir = "C:\Microsoft\AndroidNDK64"
  - ps: get-childitem -path $ndkDir
#  - ps: $url = "https://dl.google.com/android/repository/android-ndk-r15c-windows-x86_64.zip"

before_build:
  - nuget restore AndroidAppVeyor.sln

configuration: Release

build:
  project: AndroidAppVeyor.sln
  verbosity: normal
